### ISSUE TITLE
mod_pagespeed 1.3.25.4 fails to compile on OpenSUSE 12.3

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pagespeed/mod_pagespeed#701]
```
What steps will reproduce the problem?
1. Try to compile version 1.3.25.4 on OpenSUSE 12.3

What is the expected output? What do you see instead?

The build fails with

[  348s]   CXX(target) 
out/Release/obj.target/instaweb_util/net/instaweb/util/hostname_util.o
[  349s] net/instaweb/util/hostname_util.cc: In function 'GoogleString 
net_instaweb::GetHostname()':
[  349s] net/instaweb/util/hostname_util.cc:48:55: error: 'gethostname' was not 
declared in this scope
[  349s] make: *** 
[out/Release/obj.target/instaweb_util/net/instaweb/util/hostname_util.o] Error 1


What version of the product are you using (please check X-Mod-Pagespeed
header)?

1.3.25.4

On what operating system?

OpenSUSE 12.3 x86_64

$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib64/gcc/x86_64-suse-linux/4.7/lto-wrapper
Target: x86_64-suse-linux
Configured with: ../configure --prefix=/usr --infodir=/usr/share/info 
--mandir=/usr/share/man --libdir=/usr/lib64 --libexecdir=/usr/lib64 
--enable-languages=c,c++,objc,fortran,obj-c++,java,ada 
--enable-checking=release --with-gxx-include-dir=/usr/include/c++/4.7 
--enable-ssp --disable-libssp --disable-libitm --disable-plugin 
--with-bugurl=http://bugs.opensuse.org/ --with-pkgversion='SUSE Linux' 
--disable-libgcj --disable-libmudflap --with-slibdir=/lib64 --with-system-zlib 
--enable-__cxa_atexit --enable-libstdcxx-allocator=new --disable-libstdcxx-pch 
--enable-version-specific-runtime-libs --enable-linker-build-id 
--program-suffix=-4.7 --enable-linux-futex --without-system-libunwind 
--with-arch-32=i586 --with-tune=generic --build=x86_64-suse-linux
Thread model: posix
gcc version 4.7.2 20130108 [gcc-4_7-branch revision 195012] (SUSE Linux) 



```

Original issue reported on code.google.com by `robert.munteanu` on 18 May 2013 at 8:13
